package com.google.android.gms.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzmo<R extends Result> extends OptionalPendingResult<R> {
    private final zzly<R> zzagT;

    public zzmo(PendingResult<R> pendingResult) {
        if (pendingResult instanceof zzly) {
            this.zzagT = (zzly) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public R await() {
        return this.zzagT.await();
    }

    public R await(long time, TimeUnit units) {
        return this.zzagT.await(time, units);
    }

    public void cancel() {
        this.zzagT.cancel();
    }

    public R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public boolean isCanceled() {
        return this.zzagT.isCanceled();
    }

    public boolean isDone() {
        return this.zzagT.isReady();
    }

    public void setResultCallback(ResultCallback<? super R> callback) {
        this.zzagT.setResultCallback(callback);
    }

    public void setResultCallback(ResultCallback<? super R> callback, long time, TimeUnit units) {
        this.zzagT.setResultCallback(callback, time, units);
    }

    public void zza(zza com_google_android_gms_common_api_PendingResult_zza) {
        this.zzagT.zza(com_google_android_gms_common_api_PendingResult_zza);
    }

    public Integer zzoL() {
        return this.zzagT.zzoL();
    }
}
