package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class C0817B implements C0515k {
    private static final Map f1127a = new HashMap();
    private static final Map f1128b = new HashMap();
    private static final Map f1129c = new HashMap();

    public C0817B() {
        f1127a.put(cB.AGREE_AND_PAY, "Akkoord en betalen");
        f1127a.put(cB.AND_OTHER_FUNDING_SOURCES, "& overige");
        f1127a.put(cB.AUTHENTICATING, "Verificatie");
        f1127a.put(cB.BACK_BUTTON, "Achterzijde");
        f1127a.put(cB.BACKUP_FUNDING_SOURCE, "Alternatief");
        f1127a.put(cB.CANCEL, "Annuleren");
        f1127a.put(cB.CARDTYPE_AMERICANEXPRESS, "American Express");
        f1127a.put(cB.CARDTYPE_CARTAAURA, "Carta Aura");
        f1127a.put(cB.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f1127a.put(cB.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f1127a.put(cB.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f1127a.put(cB.CARDTYPE_COFINOGA, "Cofinoga");
        f1127a.put(cB.CARDTYPE_DELTA, "Delta");
        f1127a.put(cB.CARDTYPE_DISCOVER, "Discover");
        f1127a.put(cB.CARDTYPE_ELECTRON, "Electron");
        f1127a.put(cB.CARDTYPE_JCB, "JCB");
        f1127a.put(cB.CARDTYPE_MAESTRO, "Maestro");
        f1127a.put(cB.CARDTYPE_MASTERCARD, "MasterCard");
        f1127a.put(cB.CARDTYPE_POSTEPAY, "Postepay");
        f1127a.put(cB.CARDTYPE_4ETOILES, "4 étoiles");
        f1127a.put(cB.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f1127a.put(cB.CARDTYPE_VISA, "Visa");
        f1127a.put(cB.CHANGE_PAYMENT_METHOD, "Betaalmethode wijzigen");
        f1127a.put(cB.CHECKING_ACCOUNT_FOR_INSTITUTION, "Betaalrekening");
        f1127a.put(cB.CHECKING_DEVICE, "Dit apparaat wordt gecontroleerd…");
        f1127a.put(cB.CLEAR_CREDIT_CARD_INFO, "Kaartgegevens wissen");
        f1127a.put(cB.CONFIRM, "Bevestigen");
        f1127a.put(cB.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Weet u zeker dat u uw kaartgegevens wilt wissen?");
        f1127a.put(cB.CONFIRM_CHARGE_CREDIT_CARD, "Van kaart afschrijven");
        f1127a.put(cB.CONFIRM_LOG_OUT, "Weet u zeker dat u wilt uitloggen bij PayPal?");
        f1127a.put(cB.CONFIRM_SEND_PAYMENT, "Betalen");
        f1127a.put(cB.CONSENT_AGREEMENT_AGREE, "Akkoord");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Rekening gemaakt op");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Rekeningstatus");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Rekeningtype");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adres");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Leeftijdsgroep");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Geboortedatum");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-mailadres");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Volledige naam");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Geslacht");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Taal");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Gebied");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefoon");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tijdzone");
        f1127a.put(cB.CONSENT_AGREEMENT_ATTRIBUTES, "Deel het volgende: %s.");
        f1127a.put(cB.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Betaal supersnel.");
        f1127a.put(cB.CONSENT_AGREEMENT_INTRO, "%s vraagt u om:");
        f1127a.put(cB.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Deel de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalmethoden</a>.");
        f1127a.put(cB.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Betaalopties weergeven zodat u er een kunt kiezen.");
        f1127a.put(cB.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen bij %2$s die u met PayPal betaalt. U geeft PayPal opdracht alle door %3$s verzochte bedragen te betalen.");
        f1127a.put(cB.CONSENT_AGREEMENT_LOYALTY_CARD, "toestemming te verlenen onze klantenkaart aan uw PayPal Wallet toe te voegen en deze te beheren.");
        f1127a.put(cB.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Ga akkoord met het <a href='%2$s'>Privacybeleid</a> en de <a href='%3$s'>Gebruikersovereenkomst</a> van %1$s.");
        f1127a.put(cB.CONSENT_AGREEMENT_REQUEST_MONEY, "Sta toe om namens u een <a href='%1$s'>betaalverzoek</a> te doen totdat u de toestemming intrekt.");
        f1127a.put(cB.CONSENT_AGREEMENT_SEND_MONEY, "Sta toe om namens u <a href='%1$s'>geld over te maken</a> totdat u de toestemming intrekt.");
        f1127a.put(cB.CONSENT_AGREEMENT_TITLE, "Toestemming");
        f1127a.put(cB.EMAIL, "E-mail");
        f1127a.put(cB.ENVIRONMENT_MOCK_DATA, "Proefgegevens");
        f1127a.put(cB.ENVIRONMENT_SANDBOX, "Sandbox");
        f1127a.put(cB.EXPIRES_ON_DATE, "Vervaldatum");
        f1127a.put(cB.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen de betaalmethoden die beschikbaar zijn voor gebruik.</p>");
        f1127a.put(cB.FORGOT_PASSWORD, "Wachtwoord vergeten?");
        f1127a.put(cB.FROM_ACCOUNT, "Van");
        f1127a.put(cB.FUTURE_PAYMENT_METHOD_QUESTION, "Welke betaalmethode wilt u gebruiken voor toekomstige betalingen aan %1$s?");
        f1127a.put(cB.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Uw standaardbetaalbron wordt gebruikt voor toekomstige PayPal-betalingen van deze webwinkel.</p><p>U kunt deze overeenkomst annuleren door in te loggen op uw PayPal-rekening. Ga vervolgens naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> en verwijder deze webwinkel uit de lijst.</p><p>Het gedeelte Terugkerende betaling van de <a href='%s'>PayPal Gebruikersovereenkomst</a> is van toepassing.</p><p>Deze app kan een kleine testtransactie simuleren om te controleren of er betalingen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p>");
        f1127a.put(cB.INTERNAL_ERROR, "Interne fout");
        f1127a.put(cB.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Door op de knop hieronder te klikken, ga ik akkoord met de voorwaarden van de <a href='%1$s'>PayPal Gebruikersovereenkomst</a>·en verklaar ik dat ik voldoe aan de Japanse wetten en voorschriften, inclusief met betrekking tot sancties op betalingen aan Noord-Korea en Iran overeenkomstig de <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a>, bij het voltooien van de transactie.</p>");
        f1127a.put(cB.LOG_IN, "Inloggen");
        f1127a.put(cB.LOG_IN_TO_PAYPAL, "Inloggen met PayPal");
        f1127a.put(cB.LOG_OUT_BUTTON, "Uitloggen");
        f1127a.put(cB.LOG_OUT, "Uitloggen");
        f1127a.put(cB.OK, "OK");
        f1127a.put(cB.PASSWORD, "Wachtwoord");
        f1127a.put(cB.PAY_AFTER_DELIVERY, "PayPal Achteraf Betalen");
        f1127a.put(cB.PAY_WITH, "Betalen met");
        f1127a.put(cB.PAY_WITH_CARD, "Betalen met creditcard");
        f1127a.put(cB.PAYPAL_BALANCE, "PayPal-saldo");
        f1127a.put(cB.PAYPAL_CREDIT, "PayPal-krediet");
        f1127a.put(cB.PHONE, "Telefoon");
        f1127a.put(cB.PIN, "Pincode");
        f1127a.put(cB.PREFERRED_PAYMENT_METHOD, "Voorkeursbetaalmethode");
        f1127a.put(cB.PRIVACY, "PayPal beschermt uw <a href='%s'>privacy</a> en financiële gegevens.");
        f1127a.put(cB.PROCESSING, "Bezig met verwerking");
        f1127a.put(cB.REMEMBER_CARD, "Kaart onthouden");
        f1127a.put(cB.REQUEST_MONEY, "Betaalverzoek");
        f1127a.put(cB.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f1127a.put(cB.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Spaarrekening");
        f1127a.put(cB.SEND_MONEY, "Geld overmaken");
        f1127a.put(cB.SERVER_PROBLEM, "Er is een probleem opgetreden bij de communicatie met de PayPal-servers. Probeer het opnieuw.");
        f1127a.put(cB.SESSION_EXPIRED_MESSAGE, "Log opnieuw in bij PayPal.");
        f1127a.put(cB.SESSION_EXPIRED_TITLE, "Sessie verlopen");
        f1127a.put(cB.SHIPPING_ADDRESS, "Verzendadres");
        f1127a.put(cB.SIGN_UP, "Nieuw bij PayPal? Rekening openen");
        f1127a.put(cB.STAY_LOGGED_IN, "Ingelogd blijven");
        f1127a.put(cB.SYSTEM_ERROR_WITH_CODE, "Systeemfout (%s). Probeer het later opnieuw.");
        f1127a.put(cB.TRY_AGAIN, "Probeer het opnieuw");
        f1127a.put(cB.TWO_FA_REQUIRED_ERROR, "Inloggen is niet mogelijk, omdat voor uw rekening twee-factor verificatie is ingeschakeld");
        f1127a.put(cB.TWO_FACTOR_AUTH_TITLE, "Beveiligingscode");
        f1127a.put(cB.TWO_FACTOR_AUTH_SUBTITLE, "Stuur een sms naar uw telefoon. De zescijferige code die u ontvangt is 5 minuten geldig.");
        f1127a.put(cB.TWO_FACTOR_AUTH_SENDING_DIALOG, "Sms wordt gestuurd");
        f1127a.put(cB.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Voer de zescijferige beveiligingscode in");
        f1127a.put(cB.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Uw mobiele nummer");
        f1127a.put(cB.TWO_FACTOR_AUTH_SEND_SMS, "Sms sturen");
        f1127a.put(cB.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Sms opnieuw sturen");
        f1127a.put(cB.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Inloggen is niet mogelijk, omdat voor uw rekening twee-factor verificatie is ingeschakeld Ga naar de PayPal-website om uw beveiligingssleutel te activeren.");
        f1127a.put(cB.UNAUTHORIZED_DEVICE_MESSAGE, "Betalingen vanaf dit apparaat zijn niet toegestaan.");
        f1127a.put(cB.UNAUTHORIZED_DEVICE_TITLE, "Ongeautoriseerd apparaat");
        f1127a.put(cB.UNAUTHORIZED_MERCHANT_MESSAGE, "Betalingen aan deze webwinkel zijn niet toegestaan (ongeldig client-id)");
        f1127a.put(cB.UNAUTHORIZED_MERCHANT_TITLE, "Ongeldige webwinkel");
        f1127a.put(cB.UNEXPECTED_PAYMENT_FLOW, "Er is een probleem opgetreden bij de verwerking van uw betaling. Probeer het opnieuw.");
        f1127a.put(cB.UNKNOWN_FUNDING_SOURCE, "Niet-herkende bron");
        f1127a.put(cB.WE_ARE_SORRY, "Onze excuses");
        f1127a.put(cB.YOUR_ORDER, "Uw bestelling");
        f1127a.put(cB.CLEAR_CC_ALERT_TITLE, "Kaart verwijderen?");
        f1127a.put(cB.CONSENT_FAILED_ALERT_TITLE, "Toestemming mislukt");
        f1127a.put(cB.CONNECTION_FAILED_TITLE, "Verbinding mislukt");
        f1127a.put(cB.LOGIN_FAILED_ALERT_TITLE, "Inloggen mislukt");
        f1127a.put(cB.LOGIN_WITH_EMAIL, "Inloggen met wachtwoord");
        f1127a.put(cB.LOGIN_WITH_PHONE, "Inloggen met pincode");
        f1127a.put(cB.ONE_MOMENT, "Even geduld…");
        f1127a.put(cB.PAY_FAILED_ALERT_TITLE, "Betaling mislukt");
        f1127a.put(cB.SCAN_CARD_ICON_DESCRIPTION, "Scannen");
        f1127a.put(cB.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Onjuiste beveiligingscode. Probeer het opnieuw.");
        f1127a.put(cB.VIA_LABEL, "Via");
        f1127a.put(cB.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Systeemfout. Probeer het later opnieuw.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalmethoden</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Deel gegevens over de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Deel de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Deel de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalmethoden</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Deel gegevens van de aan uw PayPal-rekening gekoppelde <a href='%1$s'>betaalmethoden</a>.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Namens u de <a href='%1$s'>betaalbronnen</a> delen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen bij %2$s die u met PayPal betaalt. U geeft PayPal opdracht alle door %3$s verzochte bedragen te betalen.</p><p>Zie de <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal-overeenkomst voor terugkerende betalingen en facturen</a> voor meer informatie.</p>");
        f1128b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen bij %2$s die u met PayPal betaalt. U geeft PayPal opdracht alle door %3$s verzochte bedragen te betalen.</p><p>Zie de <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal-overeenkomst voor terugkerende betalingen en facturen</a> voor meer informatie.</p>");
        f1128b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen die u met PayPal betaalt. U geeft PayPal toestemming en opdracht alle bedragen te betalen.");
        f1128b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen die u met PayPal betaalt. U geeft PayPal toestemming en opdracht alle bedragen te betalen.");
        f1128b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen die u met PayPal betaalt. U geeft PayPal toestemming en opdracht alle bedragen te betalen.");
        f1128b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Geef vooraf toestemming voor toekomstige betalingen met uw PayPal-rekening zodat u niet steeds hoeft in te loggen. <a href='%1$s'>Zie de aanvullende voorwaarden</a> over onder andere de betaalmethoden en hoe u toekomstige betalingen kunt annuleren.");
        f1128b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Sta %2$s toe om namens u een <a href='%1$s'>betaalverzoek</a> te doen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Sta %2$s toe om namens u een <a href='%1$s'>betaalverzoek</a> te doen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Sta %2$s toe om namens u een <a href='%1$s'>betaalverzoek</a> te doen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Sta %2$s toe om namens u een <a href='%1$s'>betaalverzoek</a> te doen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Sta %2$s toe om namens u een <a href='%1$s'>betaalverzoek</a> te doen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Sta %2$s toe om namens u een <a href='%1$s'>betaalverzoek</a> te doen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Sta %2$s toe om namens u een <a href='%1$s'>betaalverzoek</a> te doen totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Sta %2$s toe om namens u <a href='%1$s'>geld over te maken</a> totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Sta %2$s toe om namens u <a href='%1$s'>geld over te maken</a> totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Sta %2$s toe om namens u <a href='%1$s'>geld over te maken</a> totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Sta %2$s toe om namens u <a href='%1$s'>geld over te maken</a> totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Sta %2$s toe om namens u <a href='%1$s'>geld over te maken</a> totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Sta %2$s toe om namens u <a href='%1$s'>geld over te maken</a> totdat u de toestemming intrekt.");
        f1128b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Sta %2$s toe om namens u <a href='%1$s'>geld over te maken</a> totdat u de toestemming intrekt.");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen de gegevens over de betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen de gegevens over de betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen de gegevens over de betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen uw betaalbronnen die beschikbaar zijn voor gebruik.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren ter controle dat er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Uw standaardbetaalmethode (uw PayPal-saldo, gekoppelde bankrekening of creditcard, in die volgorde) wordt gebruikt om voor aankopen met PayPal te betalen. Als het saldo van uw standaardbetaalmethode ontoereikend is voor de aankoop, kan uw bank of creditcardmaatschappij kosten in rekening brengen.</p><p>U kunt deze overeenkomst annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> te gaan, op <strong>Rekeninginstellingen</strong> te klikken en op <strong>Wijzigen</strong> naast ‘Inloggen met PayPal’ te klikken.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>We gebruiken uw PayPal-saldo of primaire creditcard om voor aankopen met PayPal te betalen.</p><p>U kunt deze overeenkomst annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren ter controle dat er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Uw standaardbetaalmethode wordt gebruikt om aankopen met PayPal te betalen.</p><p>U kunt deze overeenkomst annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Uw standaardbetaalbron wordt gebruikt voor toekomstige PayPal-betalingen van deze webwinkel.</p><p>U kunt deze overeenkomst annuleren door in te loggen op uw PayPal-rekening. Ga vervolgens naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> en verwijder deze webwinkel uit de lijst.</p><p>Het gedeelte Terugkerende betaling van de <a href='%s'>PayPal Gebruikersovereenkomst</a> is van toepassing.</p><p>Deze app kan een kleine testtransactie simuleren om te controleren of er betalingen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autorisatie voor toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Uw standaardbetaalmethode wordt gebruikt om aankopen met PayPal te betalen.</p><p>U kunt deze autorisatie annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p><p>Zie het gedeelte ‘Vooraf goedgekeurde betalingen’ in de <a href='%s'>PayPal Gebruikersovereenkomst</a> voor meer informatie.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorisatie voor toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Uw standaardbetaalmethode wordt gebruikt om aankopen met PayPal te betalen.</p><p>U kunt deze autorisatie annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p><p>Zie het gedeelte ‘Vooraf goedgekeurde betalingen’ in de <a href='%s'>PayPal Gebruikersovereenkomst</a> voor meer informatie.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>We gebruiken uw PayPal-saldo of primaire creditcard om voor aankopen met PayPal te betalen.</p><p>U kunt deze overeenkomst annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Autorisatie voor toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Uw standaardbetaalmethode wordt gebruikt om aankopen met PayPal te betalen.</p><p>U kunt deze autorisatie annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p><p>Zie het gedeelte ‘Vooraf goedgekeurde betalingen’ in de <a href='%s'>PayPal Gebruikersovereenkomst</a> voor meer informatie.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Autorisatie voor toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Uw standaardbetaalmethode wordt gebruikt om aankopen met PayPal te betalen.</p><p>U kunt deze autorisatie annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p><p>Zie het gedeelte ‘Vooraf goedgekeurde betalingen’ in de <a href='%s'>PayPal Gebruikersovereenkomst</a> voor meer informatie.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autorisatie voor toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van uw PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Uw standaardbetaalmethode wordt gebruikt om aankopen met PayPal te betalen.</p><p>U kunt deze autorisatie annuleren door in te loggen op uw PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p><p>Zie het gedeelte ‘Vooraf goedgekeurde betalingen’ in de <a href='%s'>PayPal Gebruikersovereenkomst</a> voor meer informatie.</p>");
        f1128b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>PayPal gebruikt eerst uw PayPal-saldo om voor uw aankoop te betalen. Als uw saldo ontoereikend is om voor het totaalbedrag te betalen, worden in volgorde eerst uw bankrekening, creditcard en vervolgens een uitgestelde bankbetaling gebruikt.</p><p>U kunt deze overeenkomst annuleren door naar www.paypal.com <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p><p>Het kan zijn dat u een kleine betaling moet autoriseren om het mogelijk te maken dat er in de toekomst bedragen van uw PayPal-rekening kunnen worden afgeschreven. De autorisatie wordt geannuleerd en er wordt niets afgeschreven.</p>");
        f1128b.put("LOG_IN_TO_PAYPAL|AU", "Inloggen met PayPal");
        f1128b.put("LOG_IN_TO_PAYPAL|GB", "Inloggen met PayPal");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de partner gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en op het instellingenicoontje te klikken. Ga naar <strong>Beveiliging</strong>, selecteer <strong>Inloggen met PayPal</strong> en verwijder deze partner.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> te gaan bij uw <strong>Profiel</strong>-instellingen en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de partner gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en op het instellingenicoontje te klikken. Ga naar <strong>Beveiliging</strong>, selecteer <strong>Inloggen met PayPal</strong> en verwijder deze partner.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de partner gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en op het instellingenicoontje te klikken. Ga naar <strong>Beveiliging</strong>, selecteer <strong>Inloggen met PayPal</strong> en verwijder deze partner.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen, in de rechterbovenhoek op het instellingenicoontje te klikken, de optie <strong>Veilig handelen</strong> te kiezen, <strong>Inloggen met PayPal</strong> te selecteren en de webwinkel te verwijderen. Als u de klassieke website nog gebruikt, gaat u naar <strong>Mijn profiel</strong> &gt; <strong>Rekeninggegevens</strong> &gt; <strong>Inloggen met PayPal</strong> en verwijdert u de webwinkel.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de partner gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en via de <strong>Profiel</strong>-instellingen naar <strong>Inloggen met PayPal</strong> te gaan en deze partner te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.it in te loggen en via <strong>Profiel</strong>, <strong>Beveiliging</strong> naar de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> te gaan bij uw <strong>Profiel</strong>-instellingen en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> te gaan bij uw <strong>Profiel</strong>-instellingen en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de partner gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.ru in te loggen, in de rechterbovenhoek op het instellingenicoontje te klikken, het tabblad <strong>Beveiliging</strong> te kiezen en deze partner te verwijderen bij de optie <strong>Inloggen met PayPal</strong>.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com.tr in te loggen, in de rechterbovenhoek op het instellingenicoontje te klikken, het tabblad <strong>Beveiliging</strong> te kiezen en deze partner te verwijderen bij de optie <strong>Inloggen met PayPal</strong>.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op uw PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1128b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>U kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f1129c.put("AMOUNT_MISMATCH", "Het totaalbedrag van items in het winkelwagentje komt niet overeen met het verkoopbedrag.");
        f1129c.put("AUTHORIZATION_ALREADY_COMPLETED", "Deze autorisatie is al voltooid.");
        f1129c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autorisatie heeft status die niet ongeldig kan worden gemaakt.");
        f1129c.put("AUTHORIZATION_EXPIRED", "Autorisatie is vervallen.");
        f1129c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "De gevraagde autorisatiereferentie bestaat niet.");
        f1129c.put("AUTHORIZATION_VOIDED", "Autorisatie is ongeldig gemaakt.");
        f1129c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Herautorisatie is alleen mogelijk van de oorspronkelijke autorisatie, niet van een herautorisatie.");
        f1129c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Herautorisatie is niet toegestaan binnen de betaalperiode.");
        f1129c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Het bedrag overschrijdt de toegestane limiet.");
        f1129c.put("CARD_TOKEN_PAYER_MISMATCH", "Toegang tot opgeslagen kaartgegevens mislukt.");
        f1129c.put("CREDIT_CARD_CVV_CHECK_FAILED", "De kaartgegevens zijn ongeldig. Corrigeer ze en verzend ze opnieuw.");
        f1129c.put("CREDIT_CARD_REFUSED", "Kaart afgewezen.");
        f1129c.put("CURRENCY_MISMATCH", "De valuta van de overboeking moet hetzelfde zijn als de autorisatievaluta.");
        f1129c.put("CURRENCY_NOT_ALLOWED", "Deze valuta wordt op dit moment niet door PayPal ondersteund.");
        f1129c.put("DATA_RETRIEVAL", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("DUPLICATE_REQUEST_ID", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("EXPIRED_CREDIT_CARD", "Kaart is verlopen");
        f1129c.put("EXPIRED_CREDIT_CARD_TOKEN", "De gegevens van deze kaart staan niet meer bij ons geregistreerd.\nVerzend de opnieuw.");
        f1129c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Functie wordt niet door leverancier ondersteund.");
        f1129c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Deze transactie is al gedeeltelijk terugbetaald.");
        f1129c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Direct betalen wordt niet ondersteund.");
        f1129c.put("INSTRUMENT_DECLINED", "De door u geselecteerde betaalmethode is niet geaccepteerd. Kies een andere betaalmethode.");
        f1129c.put("INSUFFICIENT_FUNDS", "Koper kan niet betalen - te laag saldo");
        f1129c.put("INTERNAL_SERVICE_ERROR", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("INVALID_ACCOUNT_NUMBER", "Dat rekeningnummer bestaat niet.");
        f1129c.put("INVALID_ARGUMENT", "Transactie geweigerd vanwege ongeldig argument.");
        f1129c.put("INVALID_CITY_STATE_ZIP", "Combinatie plaats/staat/postcode ongeldig");
        f1129c.put("INVALID_FACILITATOR_CONFIGURATION", "Deze transactie kan niet worden verwerkt vanwege een ongeldige facilitator-configuratie.");
        f1129c.put("INVALID_PAYER_ID", "Systeemfout: (ongeldige betalersreferentie). Probeer het later opnieuw.");
        f1129c.put("INVALID_RESOURCE_ID", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("PAYEE_ACCOUNT_INVALID", "E-mailadres van rekening leverancier is niet bevestigd.");
        f1129c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Deze leverancier kan op dit moment geen betalingen ontvangen.");
        f1129c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "E-mailadres van rekening leverancier is niet bevestigd.");
        f1129c.put("PAYEE_ACCOUNT_RESTRICTED", "Deze leverancier kan op dit moment geen betalingen ontvangen.");
        f1129c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Uw rekening is vergrendeld of gesloten.");
        f1129c.put("PAYER_ACCOUNT_RESTRICTED", "Uw rekening is beperkt.");
        f1129c.put("PAYER_CANNOT_PAY", "Deze transactie kunt u niet met PayPal betalen.");
        f1129c.put("PAYER_EMPTY_BILLING_ADDRESS", "Voor creditcardtransacties die niet via PayPal verlopen is er een factuuradres nodig.");
        f1129c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Toegang tot opgeslagen kaartgegevens mislukt.");
        f1129c.put("PAYMENT_APPROVAL_EXPIRED", "Betaalgoedkeuring is vervallen.");
        f1129c.put("PAYMENT_EXPIRED", "De betaling is vervallen.");
        f1129c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "De betaler heeft de betaling niet goedgekeurd.");
        f1129c.put("PAYMENT_REQUEST_ID_INVALID", "De referentie voor dit PayPal-verzoek is ongeldig. Probeer het later opnieuw.");
        f1129c.put("PAYMENT_STATE_INVALID", "Dit verzoek is ongeldig ten gevolge van de huidige status van de betaling.");
        f1129c.put("PERMISSION_DENIED", "Geen toestemming voor de gevraagde bewerking.");
        f1129c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "De gevraagde terugbetaling is hoger dan het bedrag van de oorspronkelijke transactie.");
        f1129c.put("REFUND_TIME_LIMIT_EXCEEDED", "Deze transactie is te oud voor terugbetaling.");
        f1129c.put("REQUIRED_SCOPE_MISSING", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("TOO_MANY_REAUTHORIZATIONS", "Er zijn geen herautorisaties meer toegestaan voor deze autorisatie.");
        f1129c.put("TRANSACTION_ALREADY_REFUNDED", "Deze transactie is al terugbetaald.");
        f1129c.put("TRANSACTION_LIMIT_EXCEEDED", "Het bedrag overschrijdt de toegestane limiet.");
        f1129c.put("TRANSACTION_REFUSED", "De transactie is geweigerd.");
        f1129c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "De transactie is geweigerd.");
        f1129c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Het profiel van de webwinkel is ingesteld om bepaalde transacties automatisch te weigeren.");
        f1129c.put("UNKNOWN_ERROR", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("UNSUPPORTED_PAYEE_COUNTRY", "Er is geen ondersteuning voor uw land.");
        f1129c.put("VALIDATION_ERROR", "De betalingsgegevens zijn ongeldig. Corrigeer ze en verzend ze opnieuw.");
        f1129c.put("ORDER_ALREADY_COMPLETED", "Bestelling is al ongeldig gemaakt, verlopen of voltooid.");
        f1129c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Het maximale aantal toegestane autorisaties voor de bestelling is bereikt.");
        f1129c.put("ORDER_VOIDED", "Uw bestelling is ongeldig gemaakt.");
        f1129c.put("ORDER_CANNOT_BE_VOIDED", "De bestelling heeft een status die verhindert dat deze ongeldig kan worden gemaakt.");
        f1129c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("UNAUTHORIZED_PAYMENT", "Deze webwinkel accepteert dit type betalingen niet.");
        f1129c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta niet ondersteund voor type creditcard.");
        f1129c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Kaarttype wordt niet ondersteund.");
        f1129c.put("ADDRESS_ADDITION_ERROR", "Er is een fout opgetreden bij het toevoegen van het verzendadres aan de PayPal-rekening.");
        f1129c.put("DUPLICATE_TRANSACTION", "Dubbele transactie.");
        f1129c.put("INVALID_SHIPPING_ADDRESS", "Het verstrekte verzendadres is ongeldig.");
        f1129c.put("PAYMENT_CREATION_ERROR", "Er is een probleem opgetreden bij het instellen van deze betaling. Ga naar de PayPal-website om uw rekening te controleren.");
        f1129c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Er is een probleem opgetreden bij het instellen van deze betaling - uw kaart is verlopen. Ga naar de PayPal-website om uw rekening te controleren.");
        f1129c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Er is een probleem opgetreden bij het instellen van deze betaling - er is een directe betaling vereist, zoals met een creditcard. Ga naar de PayPal-website om uw rekening te controleren.");
        f1129c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Er is een probleem opgetreden bij het instellen van deze betaling - de kaart moet worden bevestigd. Ga naar de PayPal-website om uw rekening te controleren.");
        f1129c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Er is een probleem opgetreden bij het instellen van deze betaling - voor deze app is het nodig een telefoon aan uw rekening toe te voegen. Ga naar de PayPal-website om uw rekening te controleren.");
        f1129c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Er is een probleem opgetreden bij het instellen van deze betaling - rekening heeft een geldige betaalbron zoals een bank- of betaalkaart nodig. Ga naar de PayPal-website om uw rekening te controleren.");
        f1129c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Er is een probleem opgetreden bij het instellen van deze betaling - u bent uw saldo nog een bedrag verschuldigd. Ga naar de PayPal-website om uw rekening te controleren.");
        f1129c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Er is een probleem opgetreden bij het instellen van deze betaling - u heeft uw verzendlimiet bereikt. Ga naar de PayPal-website om uw rekening te controleren.");
        f1129c.put("AUTH_RC_RISK_FAILURE", "Afgewezen wegens risico");
        f1129c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client niet goedgekeurd.");
        f1129c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client niet goedgekeurd.");
        f1129c.put("invalid_user", "Gebruikersnaam/wachtwoord onjuist Probeer het opnieuw.");
        f1129c.put("locked_user", "Uw PayPal-rekening is tijdelijk geblokkeerd. Probeer het later opnieuw of ga naar www.paypal.com om de blokkade direct op te heffen.");
        f1129c.put("max_attempts_exceeded", "Te veel mislukte inlogpogingen. Probeer het later opnieuw.");
        f1129c.put("invalid_request", "Er is een fout opgetreden.");
        f1129c.put("unauthorized_client", "Verzoek niet goedgekeurd");
        f1129c.put("access_denied", "Verzoek niet goedgekeurd");
        f1129c.put("unsupported_response_type", "Er is een fout opgetreden.");
        f1129c.put("invalid_scope", "Verzoek niet goedgekeurd");
        f1129c.put("server_error", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("temporarily_unavailable", "Systeemfout. Probeer het later opnieuw.");
        f1129c.put("stepup_required", "U kunt op dit moment niet inloggen. Probeer het later opnieuw of ga naar www.paypal.com om eventuele beveiligingsproblemen met uw PayPal-rekening af te handelen.");
    }

    public final String mo3720a() {
        return "nl";
    }

    public final /* synthetic */ String mo3721a(Enum enumR, String str) {
        cB cBVar = (cB) enumR;
        String str2 = cBVar.toString() + "|" + str;
        return f1128b.containsKey(str2) ? (String) f1128b.get(str2) : (String) f1127a.get(cBVar);
    }

    public final String mo3722a(String str) {
        return (String) f1129c.get(str);
    }
}
