package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class C0822G implements C0515k {
    private static final Map f1142a = new HashMap();
    private static final Map f1143b = new HashMap();
    private static final Map f1144c = new HashMap();

    public C0822G() {
        f1142a.put(cB.AGREE_AND_PAY, "Godkänn och betala");
        f1142a.put(cB.AND_OTHER_FUNDING_SOURCES, "och annan");
        f1142a.put(cB.AUTHENTICATING, "Autentisering utförs");
        f1142a.put(cB.BACK_BUTTON, "Tillbaka");
        f1142a.put(cB.BACKUP_FUNDING_SOURCE, "Reservmetod");
        f1142a.put(cB.CANCEL, "Avbryt");
        f1142a.put(cB.CARDTYPE_AMERICANEXPRESS, "American Express");
        f1142a.put(cB.CARDTYPE_CARTAAURA, "Carta Aura");
        f1142a.put(cB.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f1142a.put(cB.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f1142a.put(cB.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f1142a.put(cB.CARDTYPE_COFINOGA, "Cofinoga");
        f1142a.put(cB.CARDTYPE_DELTA, "Delta");
        f1142a.put(cB.CARDTYPE_DISCOVER, "Discover");
        f1142a.put(cB.CARDTYPE_ELECTRON, "Electron");
        f1142a.put(cB.CARDTYPE_JCB, "JCB");
        f1142a.put(cB.CARDTYPE_MAESTRO, "Maestro");
        f1142a.put(cB.CARDTYPE_MASTERCARD, "MasterCard");
        f1142a.put(cB.CARDTYPE_POSTEPAY, "Postepay");
        f1142a.put(cB.CARDTYPE_4ETOILES, "4 étoiles");
        f1142a.put(cB.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f1142a.put(cB.CARDTYPE_VISA, "Visa");
        f1142a.put(cB.CHANGE_PAYMENT_METHOD, "Ändra betalningsmetod");
        f1142a.put(cB.CHECKING_ACCOUNT_FOR_INSTITUTION, "Lönekonto");
        f1142a.put(cB.CHECKING_DEVICE, "Enheten kontrolleras …");
        f1142a.put(cB.CLEAR_CREDIT_CARD_INFO, "Ta bort kortuppgifter");
        f1142a.put(cB.CONFIRM, "Bekräfta");
        f1142a.put(cB.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Vill du ta bort kortuppgifterna?");
        f1142a.put(cB.CONFIRM_CHARGE_CREDIT_CARD, "Debitera kort");
        f1142a.put(cB.CONFIRM_LOG_OUT, "Vill du logga ut från PayPal?");
        f1142a.put(cB.CONFIRM_SEND_PAYMENT, "Betala");
        f1142a.put(cB.CONSENT_AGREEMENT_AGREE, "Godkänn");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Datum då kontot skapades");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotyp");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adress");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Åldersintervall");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Födelsedatum");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-postadress");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Fullständigt namn");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Kön");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Språk");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Språkinställning");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tidszon");
        f1142a.put(cB.CONSENT_AGREEMENT_ATTRIBUTES, "Dela det här: %s.");
        f1142a.put(cB.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Betala smidigt.");
        f1142a.put(cB.CONSENT_AGREEMENT_INTRO, "%s ber dig att:");
        f1142a.put(cB.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Dela <a href='%1$s'>betalningsmetoderna</a> som är kopplade till ditt PayPal-konto.");
        f1142a.put(cB.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Aktivera visning av dina betalningsalternativ så att du kan välja mellan dem.");
        f1142a.put(cB.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Godkänna avgifter</a> för framtida köp hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som begärs av %3$s.");
        f1142a.put(cB.CONSENT_AGREEMENT_LOYALTY_CARD, "Tillåt att de lägger till och hanterar sina lojalitetskort i din PayPal-e-plånbok.");
        f1142a.put(cB.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "godkänna <a href='%2$s'>sekretesspolicyn</a> och <a href='%3$s'>användaravtalet</a> för %1$s.");
        f1142a.put(cB.CONSENT_AGREEMENT_REQUEST_MONEY, "Tillåt dem att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1142a.put(cB.CONSENT_AGREEMENT_SEND_MONEY, "Tillåt dem att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1142a.put(cB.CONSENT_AGREEMENT_TITLE, "Medgivande");
        f1142a.put(cB.EMAIL, "E-post");
        f1142a.put(cB.ENVIRONMENT_MOCK_DATA, "Exempeldata");
        f1142a.put(cB.ENVIRONMENT_SANDBOX, "Sandbox");
        f1142a.put(cB.EXPIRES_ON_DATE, "Går ut");
        f1142a.put(cB.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilken av dina betalningsmetoder som ska användas.</p>");
        f1142a.put(cB.FORGOT_PASSWORD, "Har du glömt lösenordet?");
        f1142a.put(cB.FROM_ACCOUNT, "Från");
        f1142a.put(cB.FUTURE_PAYMENT_METHOD_QUESTION, "På vilket sätt vill du göra framtida betalningar till %1$s?");
        f1142a.put(cB.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Avtal för framtida betalningar</strong></h1><p>Dina framtida PayPal-betalningar betalas med det betalningsalternativ du angett för den här handlaren.</p><p>Om du vill upphäva avtalet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Avsnittet Återkommande betalningar i <a href='%s'>PayPals användaravtal</a> gäller.</p><p>Appen simulerar eventuellt en liten testtransaktion för att se till att du kan göra betalningar från ditt PayPal-konto, men inga pengar överförs.</p>");
        f1142a.put(cB.INTERNAL_ERROR, "Internt fel");
        f1142a.put(cB.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Genom att klicka på knappen godtar jag villkoren i <a href='%1$s'>PayPals användaravtal</a> och intygar att jag följer japanska lagar och regleringar, inklusive sanktionerna mot betalningar till Nordkorea och Iran enligt <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> för att slutföra transaktionen.</p>");
        f1142a.put(cB.LOG_IN, "Logga in");
        f1142a.put(cB.LOG_IN_TO_PAYPAL, "Logga in med PayPal");
        f1142a.put(cB.LOG_OUT_BUTTON, "Logga ut");
        f1142a.put(cB.LOG_OUT, "Logga ut");
        f1142a.put(cB.OK, "OK");
        f1142a.put(cB.PASSWORD, "Lösenord");
        f1142a.put(cB.PAY_AFTER_DELIVERY, "Betala efter leverans");
        f1142a.put(cB.PAY_WITH, "Betala med");
        f1142a.put(cB.PAY_WITH_CARD, "Betala med kort");
        f1142a.put(cB.PAYPAL_BALANCE, "PayPal-saldo");
        f1142a.put(cB.PAYPAL_CREDIT, "PayPal Credit");
        f1142a.put(cB.PHONE, "Telefon");
        f1142a.put(cB.PIN, "Pinkod");
        f1142a.put(cB.PREFERRED_PAYMENT_METHOD, "Favoritbetalningsmetod");
        f1142a.put(cB.PRIVACY, "PayPal skyddar dina <a href='%s'>personliga uppgifter</a> och dina betalningsuppgifter.");
        f1142a.put(cB.PROCESSING, "Behandling");
        f1142a.put(cB.REMEMBER_CARD, "Kom ihåg kort");
        f1142a.put(cB.REQUEST_MONEY, "Be om betalning");
        f1142a.put(cB.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f1142a.put(cB.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Sparkonto");
        f1142a.put(cB.SEND_MONEY, "Överföra pengar");
        f1142a.put(cB.SERVER_PROBLEM, "Det gick inte att kommunicera med PayPal-servrarna. Försök igen.");
        f1142a.put(cB.SESSION_EXPIRED_MESSAGE, "Logga in på PayPal igen.");
        f1142a.put(cB.SESSION_EXPIRED_TITLE, "Sessionen har upphört att gälla");
        f1142a.put(cB.SHIPPING_ADDRESS, "Leveransadress");
        f1142a.put(cB.SIGN_UP, "Har du inte använt PayPal förut? Skapa konto");
        f1142a.put(cB.STAY_LOGGED_IN, "Fortsätt att vara inloggad");
        f1142a.put(cB.SYSTEM_ERROR_WITH_CODE, "Systemfel (%s). Försök igen senare.");
        f1142a.put(cB.TRY_AGAIN, "Försök igen");
        f1142a.put(cB.TWO_FA_REQUIRED_ERROR, "Det gick inte att logga in eftersom tvåfaktorautentisering har aktiverats för ditt konto.");
        f1142a.put(cB.TWO_FACTOR_AUTH_TITLE, "Säkerhetskod");
        f1142a.put(cB.TWO_FACTOR_AUTH_SUBTITLE, "Skicka ett sms till din mobiltelefon. Den sexsiffriga koden du får är giltig i 5 minuter.");
        f1142a.put(cB.TWO_FACTOR_AUTH_SENDING_DIALOG, "Skicka sms");
        f1142a.put(cB.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Ange den sexsiffriga säkerhetskoden");
        f1142a.put(cB.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Ditt mobilnummer");
        f1142a.put(cB.TWO_FACTOR_AUTH_SEND_SMS, "Skicka sms");
        f1142a.put(cB.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Skicka sms igen");
        f1142a.put(cB.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Det gick inte att logga in eftersom tvåfaktorautentisering har aktiverats för ditt konto. Gå till PayPals webbplats för att aktivera säkerhetsnyckeln.");
        f1142a.put(cB.UNAUTHORIZED_DEVICE_MESSAGE, "Betalningar från den här enheten är inte tillåtna.");
        f1142a.put(cB.UNAUTHORIZED_DEVICE_TITLE, "Obehörig enhet");
        f1142a.put(cB.UNAUTHORIZED_MERCHANT_MESSAGE, "Betalningar till den här handlaren medges inte (ogiltigt klient-id).");
        f1142a.put(cB.UNAUTHORIZED_MERCHANT_TITLE, "Ogiltig handlare");
        f1142a.put(cB.UNEXPECTED_PAYMENT_FLOW, "Det gick inte att behandla din betalning. Försök igen.");
        f1142a.put(cB.UNKNOWN_FUNDING_SOURCE, "Okänd betalningsmetod");
        f1142a.put(cB.WE_ARE_SORRY, "Tyvärr");
        f1142a.put(cB.YOUR_ORDER, "Din order");
        f1142a.put(cB.CLEAR_CC_ALERT_TITLE, "Vill du ta bort kortet?");
        f1142a.put(cB.CONSENT_FAILED_ALERT_TITLE, "Samtycke misslyckades");
        f1142a.put(cB.CONNECTION_FAILED_TITLE, "Anslutningen misslyckades");
        f1142a.put(cB.LOGIN_FAILED_ALERT_TITLE, "Inloggningen misslyckades");
        f1142a.put(cB.LOGIN_WITH_EMAIL, "Logga in med ditt lösenord");
        f1142a.put(cB.LOGIN_WITH_PHONE, "Logga in med din pinkod");
        f1142a.put(cB.ONE_MOMENT, "Ett ögonblick …");
        f1142a.put(cB.PAY_FAILED_ALERT_TITLE, "Betalningen misslyckades");
        f1142a.put(cB.SCAN_CARD_ICON_DESCRIPTION, "Skanna");
        f1142a.put(cB.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Felaktig säkerhetskod. Försök igen.");
        f1142a.put(cB.VIA_LABEL, "Via");
        f1142a.put(cB.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Systemfel. Försök igen senare.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Dela information om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Dela informationen om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Dela information om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Dela information om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Dela information om de <a href='%1$s'>betalningsmetoder</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Dela information med dem om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Dela <a href='%1$s'>betalningsalternativen</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Dela <a href='%1$s'>betalningsalternativen</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Dela informationen om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Dela information om de <a href='%1$s'>betalningsmetoder</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Dela informationen om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Dela information om de <a href='%1$s'>betalningsmetoder</a> som är kopplade till ditt PayPal-konto.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkänna avgifter</a> för framtida köp hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som begärs av %3$s.</p><p>Mer information finns i <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPals avtal om återkommande betalningar och fakturering</a>.</p>");
        f1143b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkänna avgifter</a> för framtida köp hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som begärs av %3$s.</p><p>Mer information finns i <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPals avtal om återkommande betalningar och fakturering</a>.</p>");
        f1143b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Godkänn att pengar dras</a> för framtida köp som betalas med PayPal. Du ber PayPal betala alla belopp och godkänner detta.");
        f1143b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Godkänn att pengar dras</a> för framtida köp som betalas med PayPal. Du ber PayPal betala alla belopp och godkänner detta.");
        f1143b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Godkänn att pengar dras</a> för framtida köp som betalas med PayPal. Du ber PayPal betala alla belopp och godkänner detta.");
        f1143b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Godkänn på förhand framtida betalningar från ditt PayPal-konto utan att logga in på PayPal varje gång. <a href='%1$s'>Se fler villkor</a>, inklusive betalningsmetoder och information om hur du avbryter framtida betalningar.");
        f1143b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Tillåt %2$s att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Tillåt %2$s att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Tillåt %2$s att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Tillåt %2$s att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Tillåt %2$s att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Tillåt %2$s att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Tillåt %2$s att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Tillåt %2$s att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Tillåt %2$s att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Tillåt %2$s att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Tillåt %2$s att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Tillåt %2$s att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Tillåt %2$s att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Tillåt %2$s att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>Med appen simuleras eventuellt en liten testtransaktion för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard (PayPal-saldo, kopplat bankkonto eller betalkort, i den ordningen). Tänk på att banken eller kortutfärdaren kan ta ut en avgift om det inte finns tillräckligt med pengar för att täcka köpet.</p><p>Om du vill upphäva avtalet loggar du in på ditt PayPal-konto och går till <strong>Min profil</strong>. Klicka sedan på <strong>Mina inställningar</strong> och <strong>Ändra</strong> bredvid ”Logga in med PayPal”.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med ditt PayPal-saldo eller ditt primära betalkort.</p><p>Om du vill upphäva avtalet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill upphäva avtalet loggar du in på ditt PayPal-konto och går till <strong>Min profil</strong> &gt; <strong>Inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>Dina framtida PayPal-betalningar betalas med det betalningsalternativ du angett för den här handlaren.</p><p>Om du vill upphäva avtalet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Avsnittet Återkommande betalningar i <a href='%s'>PayPals användaravtal</a> gäller.</p><p>Appen simulerar eventuellt en liten testtransaktion för att se till att du kan göra betalningar från ditt PayPal-konto, men inga pengar överförs.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godkännande för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godkännandet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina kontoinställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Mer information finns i avsnittet ”Förgodkända betalningar” i <a href='%s'>PayPals användaravtal</a>.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkännande för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godkännandet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina kontoinställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Mer information finns i avsnittet ”Förgodkända betalningar” i <a href='%s'>PayPals användaravtal</a>.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med ditt PayPal-saldo eller ditt primära betalkort.</p><p>Om du vill upphäva avtalet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Godkännande för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godkännandet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina kontoinställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Mer information finns i avsnittet ”Förgodkända betalningar” i <a href='%s'>PayPals användaravtal</a>.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Godkännande för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godkännandet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina kontoinställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Mer information finns i avsnittet ”Förgodkända betalningar” i <a href='%s'>PayPals användaravtal</a>.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godkännande för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godkännandet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina kontoinställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Mer information finns i avsnittet ”Förgodkända betalningar” i <a href='%s'>PayPals användaravtal</a>.</p>");
        f1143b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>Vid köp dras pengar först från ditt PayPal-saldo. Om det inte täcker summan dras resterande summa från ditt bankkonto, PayPal Credit, betalkort, och/eller eCheck, i den ordningen.</p><p>Gå till www.paypal.com <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och ta bort handlaren från listan om du vill upphäva avtalet.</p><p>Det kan hända att en mindre betalning måste godkännas för att ditt PayPal-konto ska kunna debiteras i framtiden. Godkännandet annulleras sedan och du debiteras inte.</p>");
        f1143b.put("LOG_IN_TO_PAYPAL|AU", "Logga in med PayPal");
        f1143b.put("LOG_IN_TO_PAYPAL|GB", "Logga in med PayPal");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och klickar på kugghjulssymbolen. Gå till <strong>Säkerhet</strong>, välj <strong>Logga in med PayPal</strong> och ta bort den här partnern.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och klickar på kugghjulssymbolen. Gå till <strong>Säkerhet</strong>, välj <strong>Logga in med PayPal</strong> och ta bort den här partnern.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och klickar på kugghjulssymbolen. Gå till <strong>Säkerhet</strong>, välj <strong>Logga in med PayPal</strong> och ta bort den här partnern.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och klickar på kugghjulssymbolen längst upp till höger. Välj sedan <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och tar bort handlaren. Om du fortfarande använder den gamla vyn ska du gå till <strong>Min profil</strong>, välja <strong>Mina kontoinställningar</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till <strong>Min profil</strong> och tar sedan bort partnern under <strong>Logga in med PayPal</strong>.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.it och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.ru och klickar på kugghjulssymbolen längst upp till höger. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här partnern.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com.tr och klickar på kugghjulssymbolen längst upp till höger. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här partnern.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1143b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f1144c.put("AMOUNT_MISMATCH", "Totalbeloppet för objekten i kundvagnen matchar inte försäljningsbeloppet.");
        f1144c.put("AUTHORIZATION_ALREADY_COMPLETED", "Godkännandet har redan slutförts.");
        f1144c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godkännandets nuvarande status gör att det inte kan annulleras.");
        f1144c.put("AUTHORIZATION_EXPIRED", "Godkännandet har gått ut.");
        f1144c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Det id för godkännande som har begärts finns inte.");
        f1144c.put("AUTHORIZATION_VOIDED", "Ditt godkännande har annullerats.");
        f1144c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Det går endast att omgodkänna det ursprungliga godkännandet, inte ett omgodkännande.");
        f1144c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Det är inte tillåtet att omgodkänna inom garantiperioden.");
        f1144c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Beloppet överskrider den tillåtna gränsen.");
        f1144c.put("CARD_TOKEN_PAYER_MISMATCH", "Det gick inte att komma åt de sparade kortuppgifterna.");
        f1144c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortuppgifterna är ogiltiga. Korrigera och skicka igen.");
        f1144c.put("CREDIT_CARD_REFUSED", "Kortet nekades.");
        f1144c.put("CURRENCY_MISMATCH", "Inkasseringsvalutan måste vara samma som valutan för godkännandet.");
        f1144c.put("CURRENCY_NOT_ALLOWED", "Den här valutan stöds inte för närvarande av PayPal.");
        f1144c.put("DATA_RETRIEVAL", "Systemfel. Försök igen senare.");
        f1144c.put("DUPLICATE_REQUEST_ID", "Systemfel. Försök igen senare.");
        f1144c.put("EXPIRED_CREDIT_CARD", "Kortet har upphört att gälla");
        f1144c.put("EXPIRED_CREDIT_CARD_TOKEN", "Informationen för det här kortet finns inte längre sparad.\nSkicka igen.");
        f1144c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funktionen stöds inte för betalningsmottagaren.");
        f1144c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Transaktionen har delvis återbetalats.");
        f1144c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Direktbetalning stöds inte för det här.");
        f1144c.put("INSTRUMENT_DECLINED", "Den betalningsmetod du valde godkändes inte. Välj en annan betalningsmetod.");
        f1144c.put("INSUFFICIENT_FUNDS", "Köparen kan inte betala – pengar saknas.");
        f1144c.put("INTERNAL_SERVICE_ERROR", "Systemfel. Försök igen senare.");
        f1144c.put("INVALID_ACCOUNT_NUMBER", "Kontonumret finns inte.");
        f1144c.put("INVALID_ARGUMENT", "Transaktionen nekades på grund av ett ogiltigt argument");
        f1144c.put("INVALID_CITY_STATE_ZIP", "Ogiltig kombination av ort/delstat/postnummer.");
        f1144c.put("INVALID_FACILITATOR_CONFIGURATION", "Den här transaktionen kan inte behandlas på grund av ogiltig konfiguration hos partnern.");
        f1144c.put("INVALID_PAYER_ID", "Systemfel (betalarens id är ogiltigt). Försök igen senare.");
        f1144c.put("INVALID_RESOURCE_ID", "Systemfel. Försök igen senare.");
        f1144c.put("PAYEE_ACCOUNT_INVALID", "Det finns ingen bekräftad e-postadress för betalningsmottagarens konto.");
        f1144c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Den här säljaren kan inte ta emot betalningar just nu.");
        f1144c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Det finns ingen bekräftad e-postadress för betalningsmottagarens konto.");
        f1144c.put("PAYEE_ACCOUNT_RESTRICTED", "Den här säljaren kan inte ta emot betalningar just nu.");
        f1144c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Ditt konto är spärrat eller stängt.");
        f1144c.put("PAYER_ACCOUNT_RESTRICTED", "Ditt konto är begränsat.");
        f1144c.put("PAYER_CANNOT_PAY", "Du kan inte betala den här transaktionen med PayPal.");
        f1144c.put("PAYER_EMPTY_BILLING_ADDRESS", "Faktureringsadress krävs för korttransaktioner som inte görs med PayPal.");
        f1144c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Det gick inte att komma åt de sparade kortuppgifterna.");
        f1144c.put("PAYMENT_APPROVAL_EXPIRED", "Godkännandet av betalningen har upphört att gälla.");
        f1144c.put("PAYMENT_EXPIRED", "Betalningen har upphört att gälla.");
        f1144c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betalaren inte har godkänt betalningen.");
        f1144c.put("PAYMENT_REQUEST_ID_INVALID", "PayPals id för begäran är ogiltigt. Försök igen senare.");
        f1144c.put("PAYMENT_STATE_INVALID", "Denna begäran är ogiltig på grund av betalningens nuvarande status.");
        f1144c.put("PERMISSION_DENIED", "Det finns inget tillstånd för den begärda åtgärden.");
        f1144c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den begärda återbetalningen överskrider beloppet för den ursprungliga transaktionen.");
        f1144c.put("REFUND_TIME_LIMIT_EXCEEDED", "Transaktionen är för gammal för att återbetalas.");
        f1144c.put("REQUIRED_SCOPE_MISSING", "Systemfel. Försök igen senare.");
        f1144c.put("TOO_MANY_REAUTHORIZATIONS", "Inga fler omgodkännanden är tillåtna för det här godkännandet.");
        f1144c.put("TRANSACTION_ALREADY_REFUNDED", "Transaktionen har redan återbetalats.");
        f1144c.put("TRANSACTION_LIMIT_EXCEEDED", "Beloppet överskrider den tillåtna gränsen.");
        f1144c.put("TRANSACTION_REFUSED", "Transaktionen nekades.");
        f1144c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transaktionen nekades.");
        f1144c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Handlarens profil är inställd på att automatiskt neka vissa transaktioner.");
        f1144c.put("UNKNOWN_ERROR", "Systemfel. Försök igen senare.");
        f1144c.put("UNSUPPORTED_PAYEE_COUNTRY", "Landet stöds inte.");
        f1144c.put("VALIDATION_ERROR", "Betalningsuppgifterna är ogiltiga. Korrigera och skicka igen.");
        f1144c.put("ORDER_ALREADY_COMPLETED", "Beställningen har redan annullerats, gått ut eller slutförts.");
        f1144c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Högsta antal tillåtna tillstånd för beställningen har uppnåtts.");
        f1144c.put("ORDER_VOIDED", "Din order har annullerats.");
        f1144c.put("ORDER_CANNOT_BE_VOIDED", "Beställningen är i ett skede som inte medger annullering.");
        f1144c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfel. Försök igen senare.");
        f1144c.put("UNAUTHORIZED_PAYMENT", "Handlaren tar inte emot den här betalningstypen.");
        f1144c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valutan stöds inte för korttypen.");
        f1144c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen stöds inte.");
        f1144c.put("ADDRESS_ADDITION_ERROR", "Fel påträffades när en leveransadress skulle läggas till PayPal-kontot.");
        f1144c.put("DUPLICATE_TRANSACTION", "Dubblettransaktion.");
        f1144c.put("INVALID_SHIPPING_ADDRESS", "Den angivna leveransadressen är ogiltig.");
        f1144c.put("PAYMENT_CREATION_ERROR", "Det uppstod ett problem när betalningen skulle registreras. Kontrollera ditt konto på PayPals webbplats.");
        f1144c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Det uppstod ett problem när betalningen skulle registreras – kortet har upphört att gälla. Kontrollera ditt konto på PayPals webbplats.");
        f1144c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Det uppstod ett problem när betalningen skulle registreras – direktbetalning krävs, t.ex. med ett betalkort. Kontrollera ditt konto på PayPals webbplats.");
        f1144c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Det uppstod ett problem när betalningen skulle registreras – kortet måste bekräftas. Kontrollera ditt konto på PayPals webbplats.");
        f1144c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Det uppstod ett problem när betalningen skulle registreras – kontot måste innehålla ett telefonnummer enligt villkoren för appen. Kontrollera ditt konto på PayPals webbplats.");
        f1144c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Det uppstod ett problem när betalningen skulle registreras – kontot behöver en giltig betalningsmetod, t.ex. ett bankkonto eller betalkort. Kontrollera ditt konto på PayPals webbplats.");
        f1144c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Det uppstod ett problem när betalningen skulle registreras – saldot är övertrasserat. Kontrollera ditt konto på PayPals webbplats.");
        f1144c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Det uppstod ett problem när betalningen skulle registreras – du har kommit upp till överföringsgränsen. Kontrollera ditt konto på PayPals webbplats.");
        f1144c.put("AUTH_RC_RISK_FAILURE", "Nekad på grund av risk.");
        f1144c.put("AUTH_RC_OFAC_BLOCKED_IP", "Obehörig klient.");
        f1144c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Obehörig klient.");
        f1144c.put("invalid_user", "Fel användarnamn/lösenord. Försök igen.");
        f1144c.put("locked_user", "Ditt PayPal-konto har tillfälligt låsts. Försök igen senare eller gå till www.paypal.com för att låsa upp ditt PayPal-konto direkt.");
        f1144c.put("max_attempts_exceeded", "För många misslyckade inloggningsförsök. Försök igen senare.");
        f1144c.put("invalid_request", "Ett fel har inträffat.");
        f1144c.put("unauthorized_client", "Begäran medges ej.");
        f1144c.put("access_denied", "Begäran medges ej.");
        f1144c.put("unsupported_response_type", "Ett fel har inträffat.");
        f1144c.put("invalid_scope", "Begäran medges ej.");
        f1144c.put("server_error", "Systemfel. Försök igen senare.");
        f1144c.put("temporarily_unavailable", "Systemfel. Försök igen senare.");
        f1144c.put("stepup_required", "Det går inte att slutföra din inloggning just nu. Försök igen senare eller gå till www.paypal.com om du har några säkerhetsfrågor om ditt PayPal-konto.");
    }

    public final String mo3720a() {
        return "sv";
    }

    public final /* synthetic */ String mo3721a(Enum enumR, String str) {
        cB cBVar = (cB) enumR;
        String str2 = cBVar.toString() + "|" + str;
        return f1143b.containsKey(str2) ? (String) f1143b.get(str2) : (String) f1142a.get(cBVar);
    }

    public final String mo3722a(String str) {
        return (String) f1144c.get(str);
    }
}
