package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class C0855z implements C0515k {
    private static final Map f1333a = new HashMap();
    private static final Map f1334b = new HashMap();
    private static final Map f1335c = new HashMap();

    public C0855z() {
        f1333a.put(cB.AGREE_AND_PAY, "Setuju dan Bayar");
        f1333a.put(cB.AND_OTHER_FUNDING_SOURCES, "& lain");
        f1333a.put(cB.AUTHENTICATING, "Mengesahkan");
        f1333a.put(cB.BACK_BUTTON, "Undur");
        f1333a.put(cB.BACKUP_FUNDING_SOURCE, "Sandaran");
        f1333a.put(cB.CANCEL, "Batal");
        f1333a.put(cB.CARDTYPE_AMERICANEXPRESS, "American Express");
        f1333a.put(cB.CARDTYPE_CARTAAURA, "Carta Aura");
        f1333a.put(cB.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f1333a.put(cB.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f1333a.put(cB.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f1333a.put(cB.CARDTYPE_COFINOGA, "Cofinoga");
        f1333a.put(cB.CARDTYPE_DELTA, "Delta");
        f1333a.put(cB.CARDTYPE_DISCOVER, "Discover");
        f1333a.put(cB.CARDTYPE_ELECTRON, "Electron");
        f1333a.put(cB.CARDTYPE_JCB, "JCB");
        f1333a.put(cB.CARDTYPE_MAESTRO, "Maestro");
        f1333a.put(cB.CARDTYPE_MASTERCARD, "MasterCard");
        f1333a.put(cB.CARDTYPE_POSTEPAY, "Postepay");
        f1333a.put(cB.CARDTYPE_4ETOILES, "4 étoiles");
        f1333a.put(cB.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f1333a.put(cB.CARDTYPE_VISA, "Visa");
        f1333a.put(cB.CHANGE_PAYMENT_METHOD, "Tukar Kaedah Pembayaran");
        f1333a.put(cB.CHECKING_ACCOUNT_FOR_INSTITUTION, "Menyemak");
        f1333a.put(cB.CHECKING_DEVICE, "Menyemak peranti ini…");
        f1333a.put(cB.CLEAR_CREDIT_CARD_INFO, "Kosongkan maklumat kad");
        f1333a.put(cB.CONFIRM, "Sahkan");
        f1333a.put(cB.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Adakah anda pasti anda ingin mengosongkan maklumat kad anda?");
        f1333a.put(cB.CONFIRM_CHARGE_CREDIT_CARD, "Kad Caj");
        f1333a.put(cB.CONFIRM_LOG_OUT, "Adakah anda pasti anda ingin log keluar dari PayPal?");
        f1333a.put(cB.CONFIRM_SEND_PAYMENT, "Bayar");
        f1333a.put(cB.CONSENT_AGREEMENT_AGREE, "Setuju");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Tarikh Ciptaan Akaun");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Status Akaun");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Jenis Akaun");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Alamat");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Julat Umur");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Tarikh Lahir");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Alamat e-mel");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nama Penuh");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Jantina");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Bahasa");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Tempatan");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Zon Waktu");
        f1333a.put(cB.CONSENT_AGREEMENT_ATTRIBUTES, "Kongsi yang berikut: %s.");
        f1333a.put(cB.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Gunakan Daftar Keluar Lancar.");
        f1333a.put(cB.CONSENT_AGREEMENT_INTRO, "%s meminta anda:");
        f1333a.put(cB.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Kongsi <a href='%1$s'>kaedah pembayaran</a> yang dipautkan ke akaun PayPal anda.");
        f1333a.put(cB.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Aktifkan paparan pilihan pendanaan anda untuk membolehkan anda membuat pilihan.");
        f1333a.put(cB.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Benarkan caj</a> untuk pembelian %2$s pada masa depan yang dibayar melalui PayPal. Anda mengarahkan PayPal untuk membayar semua amaun yang diminta oleh %3$s.");
        f1333a.put(cB.CONSENT_AGREEMENT_LOYALTY_CARD, "Benarkan mereka menambah dan menguruskan kad kesetiaan mereka dalam dompet Paypal mereka.");
        f1333a.put(cB.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Bersetuju dengan <a href='%2$s'>dasar privasi</a> dan <a href='%3$s'>perjanjian pengguna</a> %1$s.");
        f1333a.put(cB.CONSENT_AGREEMENT_REQUEST_MONEY, "Izinkan mereka untuk <a href='%1$s'>meminta wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1333a.put(cB.CONSENT_AGREEMENT_SEND_MONEY, "Izinkan mereka untuk <a href='%1$s'>menghantar wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1333a.put(cB.CONSENT_AGREEMENT_TITLE, "Persetujuan");
        f1333a.put(cB.EMAIL, "E-mel");
        f1333a.put(cB.ENVIRONMENT_MOCK_DATA, "Data Olok-olok");
        f1333a.put(cB.ENVIRONMENT_SANDBOX, "Sandbox");
        f1333a.put(cB.EXPIRES_ON_DATE, "Tamat tempoh");
        f1333a.put(cB.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi kaedah pembayaran anda yang tersedia untuk digunakan.</p>");
        f1333a.put(cB.FORGOT_PASSWORD, "Terlupa kata laluan?");
        f1333a.put(cB.FROM_ACCOUNT, "Dari");
        f1333a.put(cB.FUTURE_PAYMENT_METHOD_QUESTION, "Bagaimanakah anda ingin membiayai bayaran masa depan kepada %1$s?");
        f1333a.put(cB.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Sumber pendanaan lalai anda akan digunakan untuk membuat bayaran PayPal masa depan daripada peniaga ini.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Bahagian Bayaran Berulang dalam <a href='%s'>Perjanjian Pengguna PayPal</a> akan diguna pakai.</p><p>Untuk memastikan bayaran boleh dibuat dengan akaun PayPal anda, aplikasi ini mungkin mensimulasikan transaksi ujian kecil, tetapi tiada wang akan dipindahkan untuk transaksi ini.</p>");
        f1333a.put(cB.INTERNAL_ERROR, "Ralat Dalaman");
        f1333a.put(cB.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Dengan mengklik butang di bawah, dengan ini saya bersetuju dengan terma-terma <a href='%1$s'>Perjanjian Pengguna PayPal</a> dan mengisytiharkan bahawa saya mematuhi undang-undang dan peraturan Jepun, termasuk sekatan terhadap bayaran ke Korea Utara dan Iran menurut <a href='%2$s'>Akta Pertukaran Asing dan Perdagangan Luar Negeri</a> untuk melengkapkan transaksi.</p>");
        f1333a.put(cB.LOG_IN, "Log Masuk");
        f1333a.put(cB.LOG_IN_TO_PAYPAL, "Log Masuk dengan PayPal");
        f1333a.put(cB.LOG_OUT_BUTTON, "Log Keluar");
        f1333a.put(cB.LOG_OUT, "Log keluar");
        f1333a.put(cB.OK, "OK");
        f1333a.put(cB.PASSWORD, "Kata Laluan");
        f1333a.put(cB.PAY_AFTER_DELIVERY, "Bayar Selepas Penghantaran");
        f1333a.put(cB.PAY_WITH, "Bayar dengan");
        f1333a.put(cB.PAY_WITH_CARD, "Bayar dengan Kad");
        f1333a.put(cB.PAYPAL_BALANCE, "Baki PayPal");
        f1333a.put(cB.PAYPAL_CREDIT, "Kredit PayPal");
        f1333a.put(cB.PHONE, "Telefon");
        f1333a.put(cB.PIN, "PIN");
        f1333a.put(cB.PREFERRED_PAYMENT_METHOD, "Kaedah Pembayaran Pilihan");
        f1333a.put(cB.PRIVACY, "PayPal melindungi <a href='%s'>privasi</a> dan maklumat kewangan anda.");
        f1333a.put(cB.PROCESSING, "Memproses");
        f1333a.put(cB.REMEMBER_CARD, "Ingat kad");
        f1333a.put(cB.REQUEST_MONEY, "Minta Wang");
        f1333a.put(cB.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak rakan kongsi.</p>");
        f1333a.put(cB.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Simpanan");
        f1333a.put(cB.SEND_MONEY, "Hantar Wang");
        f1333a.put(cB.SERVER_PROBLEM, "Terdapat masalah untuk berhubung dengan pelayan PayPal. Sila cuba semula.");
        f1333a.put(cB.SESSION_EXPIRED_MESSAGE, "Sila log masuk semula ke PayPal.");
        f1333a.put(cB.SESSION_EXPIRED_TITLE, "Sesi Telah Tamat Tempoh");
        f1333a.put(cB.SHIPPING_ADDRESS, "Alamat Pengiriman");
        f1333a.put(cB.SIGN_UP, "Baru dengan PayPal? Daftar");
        f1333a.put(cB.STAY_LOGGED_IN, "Teruskan log masuk");
        f1333a.put(cB.SYSTEM_ERROR_WITH_CODE, "Ralat sistem (%s). Sila cuba semula kemudian.");
        f1333a.put(cB.TRY_AGAIN, "Cuba Semula");
        f1333a.put(cB.TWO_FA_REQUIRED_ERROR, "Tidak dapat log masuk, kerana akaun anda telah diaktifkan dengan pengesahan dua faktor.");
        f1333a.put(cB.TWO_FACTOR_AUTH_TITLE, "Kod Keselamatan");
        f1333a.put(cB.TWO_FACTOR_AUTH_SUBTITLE, "Hantar mesej teks ke telefon anda. Kod 6 angka yang anda terima akan sah selama 5 minit.");
        f1333a.put(cB.TWO_FACTOR_AUTH_SENDING_DIALOG, "Menghantar Teks");
        f1333a.put(cB.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Masukkan kod keselamatan 6 angka");
        f1333a.put(cB.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Nombor telefon mudah alih anda");
        f1333a.put(cB.TWO_FACTOR_AUTH_SEND_SMS, "Hantar Teks");
        f1333a.put(cB.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Hantar Teks sekali lagi");
        f1333a.put(cB.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Tidak dapat log masuk, kerana akaun anda telah diaktifkan dengan pengesahan dua faktor. Sila lawati laman web PayPal untuk mengaktifkan kunci keselamatan anda.");
        f1333a.put(cB.UNAUTHORIZED_DEVICE_MESSAGE, "Bayaran dari peranti ini tidak dibenarkan.");
        f1333a.put(cB.UNAUTHORIZED_DEVICE_TITLE, "Peranti Tidak Dibenarkan");
        f1333a.put(cB.UNAUTHORIZED_MERCHANT_MESSAGE, "Bayaran kepada peniaga ini tidak dibenarkan (ID klien tidak sah).");
        f1333a.put(cB.UNAUTHORIZED_MERCHANT_TITLE, "Peniaga tidak sah");
        f1333a.put(cB.UNEXPECTED_PAYMENT_FLOW, "Terdapat masalah semasa memproses bayaran anda. Sila cuba semula.");
        f1333a.put(cB.UNKNOWN_FUNDING_SOURCE, "Sumber Tidak Dikenali");
        f1333a.put(cB.WE_ARE_SORRY, "Kami Memohon Maaf");
        f1333a.put(cB.YOUR_ORDER, "Pesanan Anda");
        f1333a.put(cB.CLEAR_CC_ALERT_TITLE, "Kosongkan Kad?");
        f1333a.put(cB.CONSENT_FAILED_ALERT_TITLE, "Persetujuan Gagal");
        f1333a.put(cB.CONNECTION_FAILED_TITLE, "Sambungan Gagal");
        f1333a.put(cB.LOGIN_FAILED_ALERT_TITLE, "Log Masuk Gagal");
        f1333a.put(cB.LOGIN_WITH_EMAIL, "Log masuk dengan kata laluan");
        f1333a.put(cB.LOGIN_WITH_PHONE, "Log masuk dengan PIN");
        f1333a.put(cB.ONE_MOMENT, "Sebentar…");
        f1333a.put(cB.PAY_FAILED_ALERT_TITLE, "Bayaran Gagal");
        f1333a.put(cB.SCAN_CARD_ICON_DESCRIPTION, "Imbas");
        f1333a.put(cB.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Kod Keselamatan Salah. Sila cuba semula.");
        f1333a.put(cB.VIA_LABEL, "Melalui");
        f1333a.put(cB.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Ralat sistem. Sila cuba semula kemudian.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Kongsi maklumat tentang <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Kongsi maklumat tentang <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Kongsi maklumat tentang <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Kongsi maklumat tentang <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Kongsi maklumat tentang <a href='%1$s'>kaedah pembayaran</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Kongsi maklumat dengan mereka tentang <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Kongsi <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Kongsi <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Kongsi maklumat tentang <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Kongsi maklumat tentang <a href='%1$s'>kaedah pembayaran</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Kongsi maklumat tentang <a href='%1$s'>sumber pendanaan</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Kongsi maklumat tentang <a href='%1$s'>kaedah pembayaran</a> yang dipautkan ke akaun PayPal anda.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Kongsi <a href='%1$s'>sumber pendanaan</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Benarkan caj</a> untuk pembelian %2$s pada masa depan yang dibayar melalui PayPal. Anda mengarahkan PayPal untuk membayar semua amaun yang diminta oleh %3$s.</p><p>Sila lihat <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Bayaran Berulang dan Perjanjian Pengebilan PayPal</a> untuk maklumat lanjut.</p>");
        f1334b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Benarkan caj</a> untuk pembelian %2$s pada masa depan yang dibayar melalui PayPal. Anda mengarahkan PayPal untuk membayar semua amaun yang diminta oleh %3$s.</p><p>Sila lihat <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Bayaran Berulang dan Perjanjian Pengebilan PayPal</a> untuk maklumat lanjut.</p>");
        f1334b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Benarkan caj</a> untuk pembelian pada masa depan yang dibayar melalui PayPal. Anda membenarkan dan mengarahkan PayPal untuk membayar semua amaun.");
        f1334b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Benarkan caj</a> untuk pembelian pada masa depan yang dibayar melalui PayPal. Anda membenarkan dan mengarahkan PayPal untuk membayar semua amaun.");
        f1334b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Benarkan caj</a> untuk pembelian pada masa depan yang dibayar melalui PayPal. Anda membenarkan dan mengarahkan PayPal untuk membayar semua amaun.");
        f1334b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Luluskan terlebih dahulu bayaran masa depan yang dibuat daripada akaun PayPal anda tanpa log masuk ke PayPal setiap kali. <a href='%1$s'>Lihat terma-terma tambahan</a>, termasuk kaedah pembayaran dan cara untuk membatalkan bayaran masa depan.");
        f1334b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Izinkan %2$s untuk <a href='%1$s'>meminta wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Izinkan %2$s untuk <a href='%1$s'>meminta wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Izinkan %2$s untuk <a href='%1$s'>meminta wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Izinkan %2$s untuk <a href='%1$s'>meminta wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Izinkan %2$s untuk <a href='%1$s'>meminta wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Izinkan %2$s untuk <a href='%1$s'>meminta wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Izinkan %2$s untuk <a href='%1$s'>meminta wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Izinkan %2$s untuk <a href='%1$s'>menghantar wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Izinkan %2$s untuk <a href='%1$s'>menghantar wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Izinkan %2$s untuk <a href='%1$s'>menghantar wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Izinkan %2$s untuk <a href='%1$s'>menghantar wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Izinkan %2$s untuk <a href='%1$s'>menghantar wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Izinkan %2$s untuk <a href='%1$s'>menghantar wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Izinkan %2$s untuk <a href='%1$s'>menghantar wang</a> bagi pihak anda sehingga anda menarik balik persetujuan.");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi maklumat tentang sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi maklumat tentang sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi maklumat tentang sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Kaedah Pembayaran</strong></h1><p>PayPal hanya berkongsi sumber pendanaan anda yang tersedia untuk digunakan.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada wang akan dipindahkan.</p><p>Kaedah pembayaran lalai anda (baki PayPal, akaun bank terpaut, kad debit atau kad kredit anda, dalam aturan tersebut) akan digunakan untuk membayar pembelian melalui PayPal. Sila ambil perhatian, jika kaedah pembayaran lalai anda tidak mempunyai wang yang cukup untuk membayar pembelian tersebut, bank atau pembekal kad anda mungkin mengenakan yuran terhadap anda.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda dan pergi ke <strong>Profil</strong>, kemudian klik <strong>Tetapan saya</strong> dan <strong>Ubah</strong> di sebelah “Log masuk dengan PayPal.”</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada wang akan dipindahkan.</p><p>Baki PayPal atau kad kredit atau kad debit utama anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda dan pergi ke <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Untuk memastikan Akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan perjanjian ini, log masuk ke Akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Sumber pendanaan lalai anda akan digunakan untuk membuat bayaran PayPal masa depan daripada peniaga ini.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Bahagian Bayaran Berulang dalam <a href='%s'>Perjanjian Pengguna PayPal</a> akan diguna pakai.</p><p>Untuk memastikan bayaran boleh dibuat dengan akaun PayPal anda, aplikasi ini mungkin mensimulasikan transaksi ujian kecil, tetapi tiada wang akan dipindahkan untuk transaksi ini.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Kebenaran Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan kebenaran ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan akaun saya</strong> &gt; <strong>Log masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Sila lihat bahagian “Bayaran Diluluskan Terlebih Dahulu” dalam <a href='%s'>Perjanjian Pengguna PayPal</a> untuk maklumat lanjut.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Kebenaran Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan kebenaran ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan akaun saya</strong> &gt; <strong>Log masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Sila lihat bahagian “Bayaran Diluluskan Terlebih Dahulu” dalam <a href='%s'>Perjanjian Pengguna PayPal</a> untuk maklumat lanjut.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada wang akan dipindahkan.</p><p>Baki PayPal atau kad kredit atau kad debit utama anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan perjanjian ini, log masuk ke akaun PayPal anda dan pergi ke <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Kebenaran Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan kebenaran ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan akaun saya</strong> &gt; <strong>Log masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Sila lihat bahagian “Bayaran Diluluskan Terlebih Dahulu” dalam <a href='%s'>Perjanjian Pengguna PayPal</a> untuk maklumat lanjut.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Kebenaran Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan kebenaran ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan akaun saya</strong> &gt; <strong>Log masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Sila lihat bahagian “Bayaran Diluluskan Terlebih Dahulu” dalam <a href='%s'>Perjanjian Pengguna PayPal</a> untuk maklumat lanjut.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Kebenaran Bayaran Masa Depan</strong></h1><p>Untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan, aplikasi ini mungkin mensimulasikan transaksi ujian kecil tetapi tiada bayaran akan dipindahkan.</p><p>Kaedah pembayaran lalai anda akan digunakan untuk membayar pembelian melalui PayPal.</p><p>Untuk membatalkan kebenaran ini, log masuk ke akaun PayPal anda, pergi ke <strong>Profil</strong> &gt; <strong>Tetapan akaun saya</strong> &gt; <strong>Log masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Sila lihat bahagian “Bayaran Diluluskan Terlebih Dahulu” dalam <a href='%s'>Perjanjian Pengguna PayPal</a> untuk maklumat lanjut.</p>");
        f1334b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Perjanjian Bayaran Masa Depan</strong></h1><p>PayPal akan menggunakan dahulu baki PayPal anda untuk membayar pembelian anda. Jika baki anda tidak mencukupi maka akaun bank, Kredit PayPal, kad debit, kad kredit dan/atau eCheck anda akan digunakan dalam pesanan tersebut.</p><p>Untuk membatalkan perjanjian ini, layari www.paypal.com <strong>Profil</strong> &gt; <strong>Tetapan Saya</strong> &gt; <strong>Log Masuk dengan PayPal</strong> dan alih keluar peniaga ini daripada senarai.</p><p>Kebenaran bayaran kecil mungkin diperlukan untuk memastikan akaun PayPal anda boleh dikenakan caj pada masa depan. Kebenaran akan dibatalkan dan anda tidak akan dikenakan caj.</p>");
        f1334b.put("LOG_IN_TO_PAYPAL|AU", "Log Masuk dengan PayPal");
        f1334b.put("LOG_IN_TO_PAYPAL|GB", "Log Masuk dengan PayPal");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan rakan kongsi.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda dan klik pada ikon gear. Pergi ke <strong>Keselamatan</strong>, pilih <strong>Log Masuk Dengan PayPal</strong> dan alih keluar rakan kongsi ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak rakan kongsi.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak rakan kongsi.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> anda dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan rakan kongsi.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda dan klik pada ikon gear. Pergi ke <strong>Keselamatan</strong>, pilih <strong>Log Masuk Dengan PayPal</strong> dan alih keluar rakan kongsi ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak rakan kongsi.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan rakan kongsi.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda dan klik pada ikon gear. Pergi ke <strong>Keselamatan</strong>, pilih <strong>Log Masuk Dengan PayPal</strong> dan alih keluar rakan kongsi ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak rakan kongsi.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda, klik pada ikon gear di sudut kanan sebelah atas, pilih <strong>Pusat Keselamatan</strong>, pilih <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga tersebut. Jika anda masih menggunakan laman web klasik, pergi ke <strong>Profil Saya</strong>, pilih <strong>Tetapan Akaun Saya</strong>, pilih <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga tersebut.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan rakan kongsi.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda, kemudian di bawah tetapan <strong>Profil</strong>, pergi ke <strong>Log Masuk dengan PayPal</strong> dan alih keluar rakan kongsi ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak rakan kongsi.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.it, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> anda dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> anda dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan rakan kongsi.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.ru, klik pada ikon gear di sudut kanan sebelah atas, pilih tab <strong>Keselamatan</strong> dan dalam pilihan <strong>Log Masuk Dengan PayPal</strong>, alih keluar rakan kongsi ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak rakan kongsi.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke akaun PayPal anda, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com.tr, klik pada ikon gear di sudut kanan sebelah atas, pilih tab <strong>Keselamatan</strong> dan dalam pilihan <strong>Log Masuk Dengan PayPal</strong>, alih keluar rakan kongsi ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke pilihan <strong>Log Masuk Dengan PayPal</strong> di bawah tetapan <strong>Profil</strong> dan alih keluar peniaga ini.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1334b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Sebarang butiran transaksi yang berkaitan akan dikongsi dengan peniaga.</p><p>Untuk menarik balik persetujuan, log masuk ke paypal.com, kemudian pergi ke <strong>Profil</strong>, <strong>Keselamatan</strong>, cari <strong>Log Masuk Dengan PayPal</strong> dan alih keluar peniaga ini.</p><p>PayPal tidak bertanggungjawab terhadap sebarang tindakan atau kesilapan pihak peniaga.</p>");
        f1335c.put("AMOUNT_MISMATCH", "Jumlah amaun item kart tidak sepadan dengan amaun jualan.");
        f1335c.put("AUTHORIZATION_ALREADY_COMPLETED", "Kebenaran ini sudah dilengkapkan.");
        f1335c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Kebenaran dalam keadaan yang tidak boleh dibatalkan.");
        f1335c.put("AUTHORIZATION_EXPIRED", "Kebenaran telah tamat tempoh.");
        f1335c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "ID kebenaran yang diminta tidak wujud.");
        f1335c.put("AUTHORIZATION_VOIDED", "Kebenaran telah dibatalkan.");
        f1335c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Hanya boleh membenarkan semula kebenaran asal, bukan kebenaran semula.");
        f1335c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Kebenaran semula tidak dibenarkan dalam tempoh penunaian.");
        f1335c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Amaun melebihi had yang dibenarkan.");
        f1335c.put("CARD_TOKEN_PAYER_MISMATCH", "Tidak boleh mengakses maklumat kad yang disimpan.");
        f1335c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Maklumat kad tidak sah. Sila betulkannya dan serahkan semula.");
        f1335c.put("CREDIT_CARD_REFUSED", "Kad ditolak.");
        f1335c.put("CURRENCY_MISMATCH", "Mata wang tahanan mesti sama dengan mata wang kebenaran.");
        f1335c.put("CURRENCY_NOT_ALLOWED", "Mata wang ini tidak disokong oleh PayPal buat masa ini.");
        f1335c.put("DATA_RETRIEVAL", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("DUPLICATE_REQUEST_ID", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("EXPIRED_CREDIT_CARD", "Kad telah tamat tempoh");
        f1335c.put("EXPIRED_CREDIT_CARD_TOKEN", "Maklumat untuk kad ini tidak lagi terdapat dalam fail.\nSila serahkan semula.");
        f1335c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Ciri tidak disokong untuk vendor ini.");
        f1335c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Sebahagian daripada transaksi ini sudah dibayar balik.");
        f1335c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Bayar segera tidak disokong untuk Tujuan yang diluluskan.");
        f1335c.put("INSTRUMENT_DECLINED", "Kaedah pembayaran yang anda pilih tidak diterima. Sila pilih kaedah berbeza.");
        f1335c.put("INSUFFICIENT_FUNDS", "Pembeli tidak dapat membayar - baki akaun tidak mencukupi.");
        f1335c.put("INTERNAL_SERVICE_ERROR", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("INVALID_ACCOUNT_NUMBER", "Nombor akaun itu tidak wujud.");
        f1335c.put("INVALID_ARGUMENT", "Transaksi ditolak kerana argumen tidak sah.");
        f1335c.put("INVALID_CITY_STATE_ZIP", "Kombinasi bandar/negeri/poskod tidak sah.");
        f1335c.put("INVALID_FACILITATOR_CONFIGURATION", "Transaksi ini tidak boleh diproses akibat konfigurasi fasilitator tidak sah.");
        f1335c.put("INVALID_PAYER_ID", "Ralat sistem (ID Pembayar tidak sah). Sila cuba semula kemudian.");
        f1335c.put("INVALID_RESOURCE_ID", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("PAYEE_ACCOUNT_INVALID", "Akaun vendor tidak mempunyai e-mel yang disahkan.");
        f1335c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Vendor ini tidak boleh menerima bayaran buat masa ini.");
        f1335c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Akaun vendor tidak mempunyai e-mel yang disahkan.");
        f1335c.put("PAYEE_ACCOUNT_RESTRICTED", "Vendor ini tidak boleh menerima bayaran buat masa ini.");
        f1335c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Akaun anda dikunci atau ditutup.");
        f1335c.put("PAYER_ACCOUNT_RESTRICTED", "Akaun anda disekat.");
        f1335c.put("PAYER_CANNOT_PAY", "Anda tidak boleh membayar transaksi ini dengan PayPal.");
        f1335c.put("PAYER_EMPTY_BILLING_ADDRESS", "Alamat pengebilan diperlukan untuk transaksi kad kredit bukan PayPal.");
        f1335c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Tidak boleh mengakses maklumat kad yang disimpan.");
        f1335c.put("PAYMENT_APPROVAL_EXPIRED", "Kelulusan bayaran telah tamat tempoh.");
        f1335c.put("PAYMENT_EXPIRED", "Bayaran telah tamat tempoh.");
        f1335c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Pembayar belum meluluskan bayaran.");
        f1335c.put("PAYMENT_REQUEST_ID_INVALID", "ID permintaan PayPal tidak sah. Sila cuba semula kemudian.");
        f1335c.put("PAYMENT_STATE_INVALID", "Permintaan ini tidak sah akibat keadaan semasa bayaran tersebut.");
        f1335c.put("PERMISSION_DENIED", "Tiada keizinan untuk operasi yang diminta.");
        f1335c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Bayaran balik yang diminta melebihi amaun transaksi asal.");
        f1335c.put("REFUND_TIME_LIMIT_EXCEEDED", "Transaksi ini terlalu lama untuk dibayar balik.");
        f1335c.put("REQUIRED_SCOPE_MISSING", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("TOO_MANY_REAUTHORIZATIONS", "Tiada lagi kebenaran semula untuk kebenaran ini dibenarkan.");
        f1335c.put("TRANSACTION_ALREADY_REFUNDED", "Transaksi ini sudah dibayar balik.");
        f1335c.put("TRANSACTION_LIMIT_EXCEEDED", "Amaun melebihi had yang dibenarkan.");
        f1335c.put("TRANSACTION_REFUSED", "Transaksi ditolak.");
        f1335c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transaksi ditolak.");
        f1335c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Keutamaan profil peniaga telah ditetapkan untuk menafikan transaksi tertentu secara automatik.");
        f1335c.put("UNKNOWN_ERROR", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("UNSUPPORTED_PAYEE_COUNTRY", "Negara anda tidak disokong.");
        f1335c.put("VALIDATION_ERROR", "Maklumat bayaran tidak sah. Sila betulkannya dan serahkan semula.");
        f1335c.put("ORDER_ALREADY_COMPLETED", "Pesanan telah dibatalkan, tamat tempoh atau dilengkapkan.");
        f1335c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Bilangan maksimum kebenaran yang dibenarkan untuk pesanan telah dicapai.");
        f1335c.put("ORDER_VOIDED", "Pesanan telah dibatalkan.");
        f1335c.put("ORDER_CANNOT_BE_VOIDED", "Pesanan dalam keadaan yang menghalang pembatalan.");
        f1335c.put("INVALID_EXPERIENCE_PROFILE_ID", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("UNAUTHORIZED_PAYMENT", "Peniaga tidak menerima jenis bayaran ini.");
        f1335c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Mata wang tidak disokong untuk jenis kad.");
        f1335c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Jenis kad tidak disokong.");
        f1335c.put("ADDRESS_ADDITION_ERROR", "Ralat ditemui semasa menambah alamat pengiriman ke akaun PayPal.");
        f1335c.put("DUPLICATE_TRANSACTION", "Transaksi duplikasi.");
        f1335c.put("INVALID_SHIPPING_ADDRESS", "Alamat penghantaran yang diberi tidak sah.");
        f1335c.put("PAYMENT_CREATION_ERROR", "Terdapat masalah semasa menyediakan bayaran ini. Sila lawati laman web PayPal untuk menyemak akaun anda.");
        f1335c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Terdapat masalah semasa menyediakan bayaran ini - kad anda telah tamat tempoh. Sila lawati laman web PayPal untuk menyemak akaun anda.");
        f1335c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Terdapat masalah semasa menyediakan bayaran ini - pembayaran serta-merta diperlukan, seperti kad kredit. Sila lawati laman web PayPal untuk menyemak akaun anda.");
        f1335c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Terdapat masalah semasa menyediakan bayaran ini - kad mesti disahkan. Sila lawati laman web PayPal untuk menyemak akaun anda.");
        f1335c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Terdapat masalah semasa menyediakan bayaran ini - aplikasi ini memerlukan akaun anda menyertakan nombor telefon. Sila lawati laman web PayPal untuk menyemak akaun anda.");
        f1335c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Terdapat masalah semasa menyediakan bayaran ini - akaun memerlukan sumber pendanaan yang sah, seperti bank atau kad pembayaran. Sila lawati laman web PayPal untuk menyemak akaun anda.");
        f1335c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Terdapat masalah semasa menyediakan bayaran ini - baki anda negatif. Sila lawati laman web PayPal untuk menyemak akaun anda.");
        f1335c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Terdapat masalah semasa menyediakan bayaran ini - had perbelanjaan anda telah dicapai. Sila lawati laman web PayPal untuk menyemak akaun anda.");
        f1335c.put("AUTH_RC_RISK_FAILURE", "Ditolak kerana terdapat risiko.");
        f1335c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klien tidak dibenarkan.");
        f1335c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klien tidak dibenarkan.");
        f1335c.put("invalid_user", "Nama pengguna/kata laluan salah. Sila cuba semula.");
        f1335c.put("locked_user", "Akaun PayPal anda telah dikunci buat sementara. Sila cuba semula kemudian atau pergi ke www.paypal.com untuk membuka kunci akaun PayPal anda dengan segera.");
        f1335c.put("max_attempts_exceeded", "Terlalu banyak cubaan log masuk gagal. Sila cuba semula kemudian.");
        f1335c.put("invalid_request", "Ralat telah berlaku.");
        f1335c.put("unauthorized_client", "Permintaan tidak dibenarkan.");
        f1335c.put("access_denied", "Permintaan tidak dibenarkan.");
        f1335c.put("unsupported_response_type", "Ralat telah berlaku.");
        f1335c.put("invalid_scope", "Permintaan tidak dibenarkan.");
        f1335c.put("server_error", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("temporarily_unavailable", "Ralat sistem. Sila cuba semula kemudian.");
        f1335c.put("stepup_required", "Log masuk anda tidak dapat dilengkapkan buat masa ini. Sila cuba semula kemudian atau pergi ke www.paypal.com untuk mengemukakan apa-apa kebimbangan tentang keselamatan dengan akaun PayPal anda.");
    }

    public final String mo3720a() {
        return "ms";
    }

    public final /* synthetic */ String mo3721a(Enum enumR, String str) {
        cB cBVar = (cB) enumR;
        String str2 = cBVar.toString() + "|" + str;
        return f1334b.containsKey(str2) ? (String) f1334b.get(str2) : (String) f1333a.get(cBVar);
    }

    public final String mo3722a(String str) {
        return (String) f1335c.get(str);
    }
}
